//
// Created by niranda on 9/22/20.
//

#ifndef CYLON_CPP_SRC_CYLON_GROUPBY_GROUPBY_AGGREGATE_OPS_HPP_
#define CYLON_CPP_SRC_CYLON_GROUPBY_GROUPBY_AGGREGATE_OPS_HPP_

namespace cylon {

enum GroupByAggregationOp {
  SUM,
  COUNT,
  MIN,
  MAX,
  MEAN
};

}

#endif //CYLON_CPP_SRC_CYLON_GROUPBY_GROUPBY_AGGREGATE_OPS_HPP_
