#ifndef TWISTERX_SRC_TWISTERX_IO_CSV_READ_CONFIG_H_
#define TWISTERX_SRC_TWISTERX_IO_CSV_READ_CONFIG_H_

#include <arrow/csv/chunker.h>

namespace twisterx {
    namespace io {
        namespace config {
            class CSVReadOptions : public arrow::csv::ReadOptions,
                                   public arrow::csv::ParseOptions,
                                   public arrow::csv::ConvertOptions {
            public:
                /**
                 * Whether to use the global CPU thread pool for reading.
                 * Default is true
                 */
                CSVReadOptions UseThreads(bool use_threads);

                /**
                 * Change the default delimiter(",")
                 * @param delimiter character representing the delimiter
                 */
                CSVReadOptions WithDelimiter(char delimiter);

                /**
                 * Ignore empty lines if any encountered while parsing
                 */
                CSVReadOptions IgnoreEmptyLines();

                /**
                 * Column names will be autogenerated and first row will
                 * not be considered as the header row
                 */
                CSVReadOptions AutoGenerateColumnNames();

                CSVReadOptions ColumnNames(std::vector<std::string> column_names);
            };
        }
    }
}
#endif //TWISTERX_SRC_TWISTERX_IO_CSV_READ_CONFIG_H_
