/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_twister2_AllToAll */

#ifndef _Included_org_twister2_AllToAll
#define _Included_org_twister2_AllToAll
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_twister2_AllToAll
 * Method:    WriteMessage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_twister2_AllToAll_WriteMessage(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
